// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asvxjrzipziopjrzytiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzdnhqcnppcHppb3Bqcnp5dGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDU0NTMsImV4cCI6MjA2NDM4MTQ1M30.gGI1aMDbBsKrK7tgw9mMfrQFuvFd5dwaQ_7dQHqcnL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);